### ISSUE TITLE
Docs!

### ISSUE THREAD

**Issue by choldgraf** [jupytercalpoly/jupyterlab-clarity-mode#12]
I wanna play around with this but I don't see any installation / usage docs or binder links. Any suggestions on how I can give this a shot?

**Comment by javag97** [comment]
What's up Chris!

Let me try to talk with Markelle and see what we can do.

**Comment by markellekelly** [comment]
Hi Chris, I added some tips for installation to the readme. Let me know if that helps!

**Comment by choldgraf** [comment]
cool, thanks!
